import os
import re

file_path = 'backend/alembic/versions/6a77cab82435_add_healthevent_model.py'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Only keep health_events and triage_sessions changes
def clean_upgrade(match):
    return '''def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('triage', 'document', 'medication', 'allergy', 'note', name='healtheventtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_ref_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_id'), 'health_events', ['id'], unique=False)
    op.create_index(op.f('ix_health_events_patient_id'), 'health_events', ['patient_id'], unique=False)
    op.add_column('triage_sessions', sa.Column('recommended_specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###'''

content = re.sub(r'def upgrade\(\) -> None:.*?# ### end Alembic commands ###', clean_upgrade, content, flags=re.DOTALL)

def clean_downgrade(match):
    return '''def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_sessions', 'recommended_specialty')
    op.drop_index(op.f('ix_health_events_patient_id'), table_name='health_events')
    op.drop_index(op.f('ix_health_events_id'), table_name='health_events')
    op.drop_table('health_events')
    # ### end Alembic commands ###'''

content = re.sub(r'def downgrade\(\) -> None:.*?# ### end Alembic commands ###', clean_downgrade, content, flags=re.DOTALL)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Migration file cleaned!")
