"""Add is_deleted to MedicalDocument

Revision ID: 0b56846ccdc7
Revises: 014f441a2d7e
Create Date: 2026-08-20 09:00:38.684216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b56846ccdc7'
down_revision: Union[str, Sequence[str], None] = '014f441a2d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_documents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_documents', 'is_deleted')
    # ### end Alembic commands ###
