"""Add SpecialistProfile

Revision ID: 194d1dfd5a9c
Revises: 6a77cab82435
Create Date: 2026-08-31 12:08:41.550592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194d1dfd5a9c'
down_revision: Union[str, Sequence[str], None] = '6a77cab82435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialist_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('availability_schedule', sa.JSON(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialist_profiles_id'), 'specialist_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_specialist_profiles_specialty'), 'specialist_profiles', ['specialty'], unique=False)
    op.create_index(op.f('ix_specialist_profiles_user_id'), 'specialist_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialist_profiles_user_id'), table_name='specialist_profiles')
    op.drop_index(op.f('ix_specialist_profiles_specialty'), table_name='specialist_profiles')
    op.drop_index(op.f('ix_specialist_profiles_id'), table_name='specialist_profiles')
    op.drop_table('specialist_profiles')
    # ### end Alembic commands ###
