"""Add HealthEvent model

Revision ID: 6a77cab82435
Revises: 0b56846ccdc7
Create Date: 2026-08-31 11:46:41.218747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a77cab82435'
down_revision: Union[str, Sequence[str], None] = '0b56846ccdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('triage', 'document', 'medication', 'allergy', 'note', name='healtheventtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('source_ref_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_id'), 'health_events', ['id'], unique=False)
    op.create_index(op.f('ix_health_events_patient_id'), 'health_events', ['patient_id'], unique=False)
    op.add_column('triage_sessions', sa.Column('recommended_specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_sessions', 'recommended_specialty')
    op.drop_index(op.f('ix_health_events_patient_id'), table_name='health_events')
    op.drop_index(op.f('ix_health_events_id'), table_name='health_events')
    op.drop_table('health_events')
    # ### end Alembic commands ###
